@p_emp_id,                                                 -- emp_id
@p_new_assigned_to_code,                                   -- assigned_to_code
@p_new_job_or_pos_id,                                      -- job_or_pos_id
@p_new_hire_date,                                          -- eff_date
@w_end_of_time,                                            -- next_eff_date
@w_employment_prior_eff_date,                              -- prior_eff_date
@w_no_value,                                               -- next_assigned_to_code
@w_no_value,                                               -- next_job_or_pos_id
@w_no_value,                                               -- prior_assigned_to_code
@w_no_value,                                               -- prior_job_or_pos_id
@p_new_hire_date,                                          -- begin_date
@p_position_end_date,                                      -- end_date
@w_no_value,                                               -- assignment_reason_code
position.organization_chart_name,                          -- organization_chart_name
position.organization_unit_name,                           -- organization_unit_name
position.organization_group_id,                            -- organization_group_id
@w_no_value,                                               -- organization_change_reason_cd
position.loc_code,                                         -- loc_code
@w_no_value,                                               -- mgr_emp_id
@w_no_value,                                               -- official_title_code
@w_end_of_time,                                            -- official_title_date
@w_end_of_time,                                            -- salary_change_date
0,                                                         -- annual_salary_amt
0,                                                         -- pd_salary_amt
@w_no_value,                                               -- pd_salary_tm_pd_id
0,                                                         -- hourly_pay_rate
@w_empl_curr_code,                                         -- curr_code
"N",                                                       -- pay_on_reported_hrs_ind
@w_no_value,                                               -- salary_change_type_code
position.standard_work_pd_id,                              -- standard_work_pd_id
position.standard_work_hrs,                                -- standard_work_hrs
position.full_tm_ind,                                      -- work_tm_code
position.work_shift_code,                                  -- work_shift_code
position.salary_structure_id,                              -- salary_structure_id
position.salary_increase_guideline_id,                     -- salary_increase_guideline_id
position.pay_grade_code,                                   -- pay_grade_code
@w_end_of_time,                                            -- pay_grade_date
position.evaluation_points_nbr,                            -- job_evaluation_points_nbr
0,                                                         -- salary_step_nbr
@w_end_of_time,                                            -- salary_step_date
@w_no_value,                                               -- phone_1_type_code
@w_no_value,                                               -- phone_1_fmt_code
@w_no_value,                                               -- phone_1_fmt_delimiter
@w_no_value,                                               -- phone_1_intl_code
@w_no_value,                                               -- phone_1_country_code
@w_no_value,                                               -- phone_1_area_city_code
@w_no_value,                                               -- phone_1_nbr
@w_no_value,                                               -- phone_1_extension_nbr
@w_no_value,                                               -- phone_2_type_code
@w_no_value,                                               -- phone_2_fmt_code
@w_no_value,                                               -- phone_2_fmt_delimiter
@w_no_value,                                               -- phone_2_intl_code
@w_no_value,                                               -- phone_2_country_code
@w_no_value,                                               -- phone_2_area_city_code
@w_no_value,                                               -- phone_2_nbr
@w_no_value,                                               -- phone_2_extension_nbr
"Y",                                                       -- prime_assignment_ind
"9",                                                       -- pay_basis_code
"3",                                                       -- occupancy_code
@w_no_value,                                               -- regulatory_reporting_unit_code
@w_no_value,                                               -- base_rate_tbl_id
@w_no_value,                                               -- base_rate_tbl_entry_code
@w_no_value,                                               -- shift_differential_rate_tbl_id
0,                                                         -- ref_annual_salary_amt
0,                                                         -- ref_pd_salary_amt
@w_no_value,                                               -- ref_pd_salary_tm_pd_id
0,                                                         -- ref_hourly_pay_rate
0,                                                         -- guaranteed_annual_salary_amt
0,                                                         -- guaranteed_pd_salary_amt
@w_no_value,                                               -- guaranteed_pd_salary_tm_pd_id
0,                                                         -- guaranteed_hourly_pay_rate
"N",                                                       -- exception_rate_ind
position.overtime_status_code,                             -- overtime_status_code
position.shift_differential_status_code,                   -- shift_differential_status_code
position.standard_daily_work_hrs,                          -- standard_daily_work_hrs
0,                                                         -- user_amt_1
0,                                                         -- user_amt_2
@w_no_value,                                               -- user_code_1
@w_no_value,                                               -- user_code_2
@w_end_of_time,                                            -- user_date_1
@w_end_of_time,                                            -- user_date_2
"N",                                                       -- user_ind_1
"N",                                                       -- user_ind_2
0,                                                         -- user_monetary_amt_1
0,                                                         -- user_monetary_amt_2
@w_empl_curr_code,                                         -- user_monetary_curr_code
@w_no_value,                                               -- user_text_1
@w_no_value,                                               -- user_text_2
@w_no_value,                                               -- unemployment_loc_code
'N',                                                       -- include_salary_in_autopay_ind
0                                                          -- chgstamp